---
- name: "ldaploadcacert | Change setting by ldaploadcacert=yes"
  authconfig: "ldaploadcacert=yes"
  register: result

- name: "ldaploadcacert | Assert 'changed'"
  assert:
    that:
      - result | changed

- name: "ldaploadcacert | Assert ' enabled' in new settings"
  assert:
    that:
      - '" enabled" in result.new_settings'

- name: "ldaploadcacert | Restore setting by ldaploadcacert=no"
  authconfig: "ldaploadcacert=no"
  register: result

- name: "ldaploadcacert | Assert 'changed'"
  assert:
    that:
      - result | changed

- name: "ldaploadcacert | Assert ' disabled' in new settings"
  assert:
    that:
      - '" disabled" in result.new_settings'

